opcao =int(input("Escolha:"))
while  opcao != 6:
    print('########################################')
    print('#           MENU PRINCIPAL             #')
    print('#                                      #')
    print('#   (1) - CADASTRAR NOVO PRODUTO       #')
    print('#   (2) - EDITAR PRODUTO               #')
    print('#   (3) - EXCLUIR PRODUTO              #')
    print('#   (4) - RELATORIO DE VENDAS          #')
    print('#   (5) - LISTA DOS PRODUTOS           #')
    print('#   (6) - SAIR DO SISTEMA              #')
    print('#                                      #')
    print('########################################')